//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class adjunto_projecto
    {
        public int cod_adjunto_projecto { get; set; }
        public string url_adjunto { get; set; }
        public string nombre_original { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<int> project_id { get; set; }
    
        public virtual project project { get; set; }
    }
}
