//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class adjunto_projecto
    {
        public int cod_adjunto_projecto { get; set; }
        public string url_adjunto { get; set; }
        public string nombre_original { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<int> project_id { get; set; }
    
        public virtual project project { get; set; }
    }
}
