//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class annotation
    {
        public string annotation_text { get; set; }
        public Nullable<double> annotation_x { get; set; }
        public Nullable<double> annotation_y { get; set; }
        public string annotation_file { get; set; }
        public int annotation_project { get; set; }
        public Nullable<double> annotation_width { get; set; }
        public Nullable<double> annotation_height { get; set; }
        public bool annotation_folded { get; set; }
        public bool annotation_readonly { get; set; }
        public string annotation_type { get; set; }
        public string annotation_displayformat { get; set; }
        public string annotation_id { get; set; }
    }
}
