//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class annotation
    {
        public string annotation_text { get; set; }
        public Nullable<double> annotation_x { get; set; }
        public Nullable<double> annotation_y { get; set; }
        public string annotation_file { get; set; }
        public int annotation_project { get; set; }
        public Nullable<double> annotation_width { get; set; }
        public Nullable<double> annotation_height { get; set; }
        public bool annotation_folded { get; set; }
        public bool annotation_readonly { get; set; }
        public string annotation_type { get; set; }
        public string annotation_displayformat { get; set; }
        public string annotation_id { get; set; }
    }
}
