//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public attachment()
        {
            this.project_attachment = new HashSet<project_attachment>();
        }
    
        public int attachment_id { get; set; }
        public int attachment_father_id { get; set; }
        public string attachment_name { get; set; }
        public string attachment_machine_name { get; set; }
        public string attachment_description { get; set; }
        public string attachment_format { get; set; }
        public int attachment_quantity { get; set; }
        public Nullable<int> attachment_order { get; set; }
        public byte attachment_deleted { get; set; }
        public Nullable<int> attachment_foreing_producer { get; set; }
        public string tooltip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_attachment> project_attachment { get; set; }
    }
}
