//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachment_view
    {
        public int attachment_id { get; set; }
        public string attachment_name { get; set; }
        public string attachment_description { get; set; }
        public Nullable<int> attachment_foreing_producer { get; set; }
        public string attachment_section { get; set; }
        public string attachment_format { get; set; }
        public Nullable<int> attachment_order { get; set; }
    }
}
