//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachment_validation
    {
        public int validation_id { get; set; }
        public Nullable<int> attachment_id { get; set; }
        public string variable { get; set; }
        public string validation_type { get; set; }
        public string value { get; set; }
        public string @operator { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<int> prioridad { get; set; }
    }
}
