//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachment_validation
    {
        public int validation_id { get; set; }
        public Nullable<int> attachment_id { get; set; }
        public string variable { get; set; }
        public string validation_type { get; set; }
        public string value { get; set; }
        public string @operator { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<int> prioridad { get; set; }
    }
}
