//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class especialidad_cargo
    {
        public int id_especialidad_cargo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> position_id { get; set; }
    
        public virtual position position { get; set; }
    }
}
