//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class especialidad_cargo
    {
        public int id_especialidad_cargo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> position_id { get; set; }
    
        public virtual position position { get; set; }
    }
}
