//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class estimulo
    {
        public int id_estimulo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> id_tipo_estimulo { get; set; }
        public Nullable<double> valor { get; set; }
        public string beneficiario { get; set; }
    
        public virtual tipo_estimulo tipo_estimulo { get; set; }
        public virtual project project { get; set; }
    }
}
