//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class estimulo
    {
        public int id_estimulo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> id_tipo_estimulo { get; set; }
        public Nullable<double> valor { get; set; }
        public string beneficiario { get; set; }
    
        public virtual project project { get; set; }
        public virtual tipo_estimulo tipo_estimulo { get; set; }
    }
}
