//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class letter
    {
        public int letter_id { get; set; }
        public string letter_body { get; set; }
        public string letter_message { get; set; }
        public string letter_greeting { get; set; }
        public string letter_note { get; set; }
        public string letter_prefirma { get; set; }
    }
}
