//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class letter
    {
        public int letter_id { get; set; }
        public string letter_body { get; set; }
        public string letter_message { get; set; }
        public string letter_greeting { get; set; }
        public string letter_note { get; set; }
        public string letter_prefirma { get; set; }
    }
}
