//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class localization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public localization()
        {
            this.producer = new HashSet<producer>();
            this.project_staff = new HashSet<project_staff>();
        }
    
        public string localization_id { get; set; }
        public string localization_father_id { get; set; }
        public string localization_name { get; set; }
        public Nullable<decimal> localization_x_coord { get; set; }
        public Nullable<decimal> localization_y_coord { get; set; }
        public string localization_description { get; set; }
        public byte localization_deleted { get; set; }
        public Nullable<int> COD_ZONA_COLOMBIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producer> producer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_staff> project_staff { get; set; }
    }
}
