//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cineEntities : DbContext
    {
        public cineEntities()
            : base("name=cineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adjunto_projecto> adjunto_projecto { get; set; }
        public virtual DbSet<annotation> annotation { get; set; }
        public virtual DbSet<attachment> attachment { get; set; }
        public virtual DbSet<configuration> configuration { get; set; }
        public virtual DbSet<correo> correo { get; set; }
        public virtual DbSet<firma_tramite> firma_tramite { get; set; }
        public virtual DbSet<format> format { get; set; }
        public virtual DbSet<format_type> format_type { get; set; }
        public virtual DbSet<formato_captura> formato_captura { get; set; }
        public virtual DbSet<identification_type> identification_type { get; set; }
        public virtual DbSet<idioma> idioma { get; set; }
        public virtual DbSet<letter> letter { get; set; }
        public virtual DbSet<localization> localization { get; set; }
        public virtual DbSet<permission> permission { get; set; }
        public virtual DbSet<person_type> person_type { get; set; }
        public virtual DbSet<personal_type> personal_type { get; set; }
        public virtual DbSet<position> position { get; set; }
        public virtual DbSet<producer_company_type> producer_company_type { get; set; }
        public virtual DbSet<producer_type> producer_type { get; set; }
        public virtual DbSet<production_type> production_type { get; set; }
        public virtual DbSet<project_attachment> project_attachment { get; set; }
        public virtual DbSet<project_format> project_format { get; set; }
        public virtual DbSet<project_genre> project_genre { get; set; }
        public virtual DbSet<project_optional_staff> project_optional_staff { get; set; }
        public virtual DbSet<project_responsable> project_responsable { get; set; }
        public virtual DbSet<project_status> project_status { get; set; }
        public virtual DbSet<project_type> project_type { get; set; }
        public virtual DbSet<request_form> request_form { get; set; }
        public virtual DbSet<resolution> resolution { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<role_assignment> role_assignment { get; set; }
        public virtual DbSet<role_permission> role_permission { get; set; }
        public virtual DbSet<section> section { get; set; }
        public virtual DbSet<staff_option> staff_option { get; set; }
        public virtual DbSet<staff_option_detail> staff_option_detail { get; set; }
        public virtual DbSet<state> state { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tooltip> tooltip { get; set; }
        public virtual DbSet<ZONA_COLOMBIA> ZONA_COLOMBIA { get; set; }
        public virtual DbSet<attachment_validation> attachment_validation { get; set; }
        public virtual DbSet<attachment_view> attachment_view { get; set; }
        public virtual DbSet<etnia> etnia { get; set; }
        public virtual DbSet<genero> genero { get; set; }
        public virtual DbSet<project_staff> project_staff { get; set; }
        public virtual DbSet<grupo_poblacional> grupo_poblacional { get; set; }
        public virtual DbSet<estimulo> estimulo { get; set; }
        public virtual DbSet<tipo_estimulo> tipo_estimulo { get; set; }
        public virtual DbSet<project_producer> project_producer { get; set; }
        public virtual DbSet<dia_feriado> dia_feriado { get; set; }
        public virtual DbSet<especialidad_cargo> especialidad_cargo { get; set; }
        public virtual DbSet<project> project { get; set; }
        public virtual DbSet<producer> producer { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
