//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal_type
    {
        public int personal_type_id { get; set; }
        public string personal_type_name { get; set; }
        public Nullable<int> personal_type_deleted { get; set; }
    }
}
