//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class producer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producer()
        {
            this.project_producer = new HashSet<project_producer>();
        }
    
        public int producer_id { get; set; }
        public Nullable<int> person_type_id { get; set; }
        public Nullable<int> identification_type_id { get; set; }
        public string producer_name { get; set; }
        public string producer_nit { get; set; }
        public Nullable<int> producer_company_type_id { get; set; }
        public Nullable<int> producer_type_id { get; set; }
        public string producer_identification_number { get; set; }
        public string producer_firstname { get; set; }
        public string producer_lastname { get; set; }
        public string producer_localization_id { get; set; }
        public string producer_country { get; set; }
        public string producer_city { get; set; }
        public string producer_address { get; set; }
        public string producer_phone { get; set; }
        public string producer_fax { get; set; }
        public string producer_movil { get; set; }
        public string producer_email { get; set; }
        public string producer_website { get; set; }
        public Nullable<int> producer_user_id { get; set; }
        public string producer_firstname2 { get; set; }
        public string producer_lastname2 { get; set; }
        public Nullable<int> id_genero { get; set; }
        public Nullable<int> id_etnia { get; set; }
        public Nullable<int> producer_nit_dig_verif { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<int> id_grupo_poblacional { get; set; }
        public string abreviatura { get; set; }
        public string primer_nombre_sup { get; set; }
        public string segundo_nombre_sup { get; set; }
        public string primer_apellido_sup { get; set; }
        public string segundo_apellido_sup { get; set; }
        public string num_id_sup { get; set; }
        public Nullable<int> identification_type_id_sup { get; set; }
        public string PRODUCTOR_PAIS_CONTACTO { get; set; }
        public string PRODUCTOR_CIUDAD_CONTACTO { get; set; }
        public string PRODUCTOR_LOCALIZACION_CONTACTO_ID { get; set; }
    
        public virtual etnia etnia { get; set; }
        public virtual genero genero { get; set; }
        public virtual identification_type identification_type { get; set; }
        public virtual person_type person_type { get; set; }
        public virtual producer_company_type producer_company_type { get; set; }
        public virtual producer_type producer_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_producer> project_producer { get; set; }
        public virtual localization localization { get; set; }
    }
}
