//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_producer
    {
        public int project_producer_id { get; set; }
        public int producer_id { get; set; }
        public int project_id { get; set; }
        public Nullable<double> project_producer_participation_percentage { get; set; }
        public int project_producer_requester { get; set; }
    
        public virtual producer producer { get; set; }
        public virtual project project { get; set; }
    }
}
