//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_attachment
    {
        public int project_attachment_id { get; set; }
        public int project_attachment_attachment_id { get; set; }
        public int project_attachment_project_id { get; set; }
        public string project_attachment_path { get; set; }
        public string project_attachment_observation { get; set; }
        public System.DateTime project_attachment_date { get; set; }
        public byte project_attachment_approved { get; set; }
        public Nullable<int> project_attachment_producer_id { get; set; }
        public Nullable<int> project_attachment_project_staff_order { get; set; }
        public string nombre_original { get; set; }
        public Nullable<int> project_staff_id { get; set; }
    
        public virtual attachment attachment { get; set; }
        public virtual project project { get; set; }
    }
}
