//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_responsable
    {
        public int id_project_responsable { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> responsable { get; set; }
        public Nullable<int> asignado_por { get; set; }
        public Nullable<int> project_id { get; set; }
    
        public virtual project project { get; set; }
    }
}
