//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_format
    {
        public int format_id { get; set; }
        public int project_id { get; set; }
        public string project_format_detail { get; set; }
    
        public virtual format format { get; set; }
        public virtual project project { get; set; }
    }
}
