//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_status
    {
        public int project_status_project_id { get; set; }
        public int project_status_section_id { get; set; }
        public int project_status_revision_state_id { get; set; }
        public Nullable<int> project_status_tab_state_id { get; set; }
        public string project_status_revision_mark { get; set; }
        public string project_status_solicitud_aclaraciones { get; set; }
        public Nullable<System.DateTime> project_status_solicitud_aclaraciones_date { get; set; }
        public string project_status_observacion_inicial { get; set; }
        public Nullable<System.DateTime> project_status_observacion_inicial_date { get; set; }
        public string project_status_aclaraciones_productor { get; set; }
        public Nullable<System.DateTime> project_status_aclaraciones_productor_date { get; set; }
        public string project_status_observacion_final { get; set; }
        public Nullable<System.DateTime> project_status_observacion_final_date { get; set; }
        public Nullable<System.DateTime> project_status_modified { get; set; }
        public Nullable<System.DateTime> project_status_viewed { get; set; }
    
        public virtual project project { get; set; }
        public virtual section section { get; set; }
    }
}
