//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_attachment
    {
        public int project_attachment_id { get; set; }
        public int project_attachment_attachment_id { get; set; }
        public int project_attachment_project_id { get; set; }
        public string project_attachment_path { get; set; }
        public string project_attachment_observation { get; set; }
        public System.DateTime project_attachment_date { get; set; }
        public byte project_attachment_approved { get; set; }
        public Nullable<int> project_attachment_producer_id { get; set; }
        public Nullable<int> project_attachment_project_staff_order { get; set; }
        public string nombre_original { get; set; }
        public Nullable<int> project_staff_id { get; set; }
    
        public virtual attachment attachment { get; set; }
        public virtual project project { get; set; }
    }
}
