//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_format
    {
        public int format_id { get; set; }
        public int project_id { get; set; }
        public string project_format_detail { get; set; }
    
        public virtual format format { get; set; }
        public virtual project project { get; set; }
    }
}
