//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class resolution
    {
        public int resolution_id { get; set; }
        public string resolution_path { get; set; }
        public int project_id { get; set; }
        public System.DateTime resolution_uploaded { get; set; }
        public int resolution_visible { get; set; }
        public string resolution_path2 { get; set; }
        public Nullable<System.DateTime> resolution_uploaded2 { get; set; }
    
        public virtual project project { get; set; }
    }
}
