//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class resolution
    {
        public int resolution_id { get; set; }
        public string resolution_path { get; set; }
        public int project_id { get; set; }
        public System.DateTime resolution_uploaded { get; set; }
        public int resolution_visible { get; set; }
        public string resolution_path2 { get; set; }
        public Nullable<System.DateTime> resolution_uploaded2 { get; set; }
    
        public virtual project project { get; set; }
    }
}
