//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_log
    {
        public int id { get; set; }
        public string accion { get; set; }
        public string detalle { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
