//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_option_detail
    {
        public int staff_option_detail_id { get; set; }
        public int staff_option_id { get; set; }
        public int position_id { get; set; }
        public int staff_option_detail_quantity { get; set; }
        public int staff_option_detail_optional_quantity { get; set; }
        public byte staff_option_detail_deleted { get; set; }
        public Nullable<int> version { get; set; }
    
        public virtual position position { get; set; }
        public virtual staff_option staff_option { get; set; }
    }
}
