//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_option
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff_option()
        {
            this.project = new HashSet<project>();
            this.staff_option_detail = new HashSet<staff_option_detail>();
        }
    
        public int staff_option_id { get; set; }
        public int project_type_id { get; set; }
        public int production_type_id { get; set; }
        public int project_genre_id { get; set; }
        public byte staff_option_has_domestic_director { get; set; }
        public string staff_option_description { get; set; }
        public byte staff_option_deleted { get; set; }
        public Nullable<int> staff_option_percentage_init { get; set; }
        public Nullable<int> staff_option_percentage_end { get; set; }
        public Nullable<int> staff_option_personal_option { get; set; }
    
        public virtual production_type production_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> project { get; set; }
        public virtual project_type project_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<staff_option_detail> staff_option_detail { get; set; }
    }
}
