//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_option
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff_option()
        {
            this.staff_option_detail = new HashSet<staff_option_detail>();
            this.project = new HashSet<project>();
        }
    
        public int staff_option_id { get; set; }
        public int project_type_id { get; set; }
        public int production_type_id { get; set; }
        public int project_genre_id { get; set; }
        public byte staff_option_has_domestic_director { get; set; }
        public string staff_option_description { get; set; }
        public byte staff_option_deleted { get; set; }
        public Nullable<int> staff_option_percentage_init { get; set; }
        public Nullable<int> staff_option_percentage_end { get; set; }
        public Nullable<int> staff_option_personal_option { get; set; }
    
        public virtual production_type production_type { get; set; }
        public virtual project_type project_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<staff_option_detail> staff_option_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> project { get; set; }
    }
}
