//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_format
    {
        public Nullable<int> project_id { get; set; }
        public string staff_format_position { get; set; }
        public string staff_format_name { get; set; }
        public string staff_format_identification_number { get; set; }
        public string staff_format_address { get; set; }
        public string staff_format_localization_id { get; set; }
        public string staff_format_country { get; set; }
        public string staff_format_state { get; set; }
        public string staff_format_email { get; set; }
        public string staff_format_phone { get; set; }
        public string staff_format_movil { get; set; }
        public string staff_format_fax { get; set; }
        public int Id_new { get; set; }
    
        public virtual project project { get; set; }
    }
}
