//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioCineProducto.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_format
    {
        public Nullable<int> project_id { get; set; }
        public string staff_format_position { get; set; }
        public string staff_format_name { get; set; }
        public string staff_format_identification_number { get; set; }
        public string staff_format_address { get; set; }
        public string staff_format_localization_id { get; set; }
        public string staff_format_country { get; set; }
        public string staff_format_state { get; set; }
        public string staff_format_email { get; set; }
        public string staff_format_phone { get; set; }
        public string staff_format_movil { get; set; }
        public string staff_format_fax { get; set; }
        public int Id_new { get; set; }
    
        public virtual project project { get; set; }
    }
}
